### ISSUE TITLE
Trello Deprecation Error - Wildcard ("*") allowed origins are no longer supported.

### ISSUE THREAD

**Issue by jclevine** [schwittmann/pebble-trello2#5]
When you try to setup the app you get the error:

```
Invalid return_url. Wildcard ("*") allowed origins are no longer supported. Contact the developer. See https://community.developer.atlassian.com/t/52093
```

The app needs to change the allowed origin to be https://pebble-trello.appspot.com/

**Comment by schwittmann** [comment]
Thanks for reporting. I just changed the origin accordingly, please check if the problem has been fixed

**Comment by jclevine** [comment]
Fixed! Thanks!
